#
# ~/.bash_aliases
#

alias ls='ls --color=always'
alias killemacs='emacsclient -e "(kill-emacs)"'
alias emacs='emacsclient -c'
alias e='emacs -nw'
alias grep='grep --color=always'
alias less='less --RAW-CONTROL-CHARS --chop-long-lines --LONG-PROMPT'
alias cp='cp --interactive'
alias mv='mv --interactive'
alias rm='rm --interactive'
alias '?'='history'
alias df='df --human-readable'
alias du='du --human-readable'
alias ..='cd ..'
alias ...='cd ../..'
alias lynx='lynx --display_charset=utf8'

#
# Drush
#

# Save the current directory, go to www directory, execute the command
# and restore the saved directory.
function pushd_command_popd() { pushd . > /dev/null; cd ~/www; $@; popd > /dev/null; }

alias d='pushd_command_popd drush'
alias sd='sudo -u www-data drush'
alias c='pushd_command_popd sudo -u www-data drush cc all'

#
# Phing
#

alias up='phing update'

#
# SVN
#

alias svnup='svn update --ignore-externals'
alias svnst='svn status --ignore-externals'
function svndiff() { \svn diff | colordiff | less; }
function cdiff() { \diff -u $@ | colordiff | less; }
