---
- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - curl
    - unzip
    - bzip2
    - subversion
    - mariadb-server
    - libmysqlclient-dev
    - apache2
    - php5
    - php5-mysql
    - php5-curl
    - php5-gd
    - emacs-nox

- name: Install the Python MySQLB module
  pip: name=MySQL-python

- name: Create database
  mysql_db: name=vagrant state=present

- name: Create user and set privileges
  mysql_user: name=vagrant password=vagrant priv=vagrant.*:ALL state=present

- stat: path=/var/www/html
  register: www

- file: path=/var/www/html state=absent
  when: www.stat.isdir is defined and www.stat.isdir

- file: src=/vagrant/www dest=/var/www/html state=link force=yes

- apache2_module: state=present name=rewrite

- name: Configure Apache
  copy: src=apache2.conf
        dest=/etc/apache2/apache2.conf
        owner=root group=root mode=0644
  notify: Restart Apache
