---
- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - curl
    - unzip
    - bzip2
    - mariadb-server
    - apache2
    - php5
    - php5-mysql
    - php5-curl
    - php5-gd

- name: Create database
  mysql_db: name=vagrant state=present

- name: Create user and set privileges
  mysql_user: name=vagrant password=vagrant priv=vagrant.*:ALL state=present

- stat: path=/var/www/html
  register: www

- file: path=/var/www/html state=absent
  when: www.stat.isdir is defined and www.stat.isdir

- file: src=/vagrant/www dest=/var/www/html state=link force=yes

- apache2_module: state=present name=rewrite

- name: Configure Apache
  copy: src=apache2/apache2.conf
        dest=/etc/apache2/apache2.conf
        owner=root group=root mode=0644
  notify: Restart Apache

- copy: src=apache2/envvars
        dest=/etc/apache2/envvars
        owner=root group=root mode=0644
  notify: Restart Apache

- file: path=/home/vagrant/.ssh state=directory
        owner=vagrant group=vagrant mode=0755

- name: Configure SSH
  copy: src=ssh_config
        dest=/home/vagrant/.ssh/config
        owner=vagrant group=vagrant mode=0644

- name: Configure PHP
  copy: src=php.ini
        dest=/etc/php5/apache2/php.ini
        owner=root group=root mode=0644
  notify: Restart Apache
